name: tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.6'
      - name: Install dependencies
        run: go get -u ./...

      - name: Build Legion Bot
        run: go build -o ./cmd/legionbot/legionbot ./cmd/legionbot/*.go

      - name: Test with the Go CLI
        run: go test -race ./...
